### ISSUE TITLE
Add documentation for Event model 

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-data-models#3]
draft documentation is here https://docs.google.com/document/d/1AGgXOurIRzbrlOQHgB92thxGoyk0zcb9NJyviPaZp-U/edit#heading=h.ytm29lx9045

**Comment by emetsger** [comment]
Placeholders for canonical documentation are in place.  My understanding is that they will be filled in using the [event doc](https://docs.google.com/document/d/1AGgXOurIRzbrlOQHgB92thxGoyk0zcb9NJyviPaZp-U/edit#heading=h.ytm29lx9045) as a guide during implementation.

As implementation occurs, PRs can be submitted against master and reviewed/compared against the guide.  Any discussion around deviations to the guide can occur on the PR, or out-of-band.

If that matches your understanding @htpvu then I think this issue can be closed.
